# Generated by Django 5.0 on 2024-05-31 07:49

import django.db.models.deletion
import froala_editor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0018_alter_fielddata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('status', models.CharField(choices=[('Open', 'Открыта'), ('Closed', 'Закрыта')], default='Open', max_length=10)),
                ('result', models.CharField(choices=[('Sale', 'Продажа'), ('Buy', 'Покупка'), ('Order', 'Заказ'), ('Consultation', 'Консультация'), ('Refusal', 'Отказ'), ('Other', 'Другое')], default='Other', max_length=15)),
                ('comment', froala_editor.fields.FroalaField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='services.templateform')),
            ],
        ),
    ]
