# Generated by Django 5.0 on 2024-05-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0002_remove_callbackdetail_comment_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbackdetail',
            name='template',
        ),
        migrations.AlterField(
            model_name='callbackdetail',
            name='uid',
            field=models.IntegerField(unique=True),
        ),
    ]
