version: '3'

services:
  db_pochtman:
    container_name: db_pochtman
    image: postgres:latest
    environment:
      POSTGRES_DB: pochtman
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d pochtman" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_pochtman_data:/var/lib/postgresql/data/

  redis_pochtman:
    image: redis:latest
    container_name: redis_pochtman
    ports:
      - "6379:6379"

  web_pochtman:
    env_file:
      - .env
    build:
      context: .
    restart: always
    volumes:
      - .:/code
      - static-pochtman_data:/vol/static/
    ports:
      - "8000:8000"
    depends_on:
      - db_pochtman
      - redis_pochtman
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      DATABASE_URL: postgres://postgres:postgres@db_pochtman:5432/pochtman
      REDIS_URL: redis://redis_pochtman:6379/0
      FERNET_KEY: ${FERNET_KEY}
      SECRET_KEY: ${SECRET_KEY}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      EMAIL_BACKEND: ${EMAIL_BACKEND}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}

  celery-worker_pochtman:
    build:
      context: .
    container_name: celery-worker_pochtman
    entrypoint: celery
    command: -A core worker --loglevel=info
    depends_on:
      - redis_pochtman
    restart: on-failure
    working_dir: /code/Mail_Service/

  celery-beat_pochtman:
    build:
      context: .
    container_name: celery-beat_pochtman
    entrypoint: celery
    command: -A core beat --loglevel=info
    depends_on:
      - redis_pochtman
    restart: on-failure
    working_dir: /code/Mail_Service/

  flower_pochtman:
    image: mher/flower
    container_name: flower_pochtman
    command: celery flower --broker=redis://redis_pochtman:6379/0 --port=5555
    environment:
      - CELERY_BROKER_URL=redis://redis_pochtman:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis_pochtman
    restart: always

  nginx_pochtman:
    image: nginx:latest
    build:
      context: ./proxy
    restart: always
    volumes:
      - static-pochtman_data:/vol/static/
    ports:
      - "80:80"
    depends_on:
      - web_pochtman

volumes:
  db_pochtman_data:
  static-pochtman_data: