version: '3'

services:
  db_pochtman:
    container_name: db_pochtman
    image: postgres:latest
    environment:
      POSTGRES_DB: pochtman
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d pochtman" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_pochtman_data:/var/lib/postgresql/data/

  redis_pochtman:
    image: redis:latest
    container_name: redis_pochtman
    ports:
      - "6379:6379"

  web_pochtman:
    build:
      context: .
    restart: always
    volumes:
      - .:/code
      - static-pochtman_data:/vol/static/
    ports:
      - "8000:8000"
    depends_on:
      - db_pochtman
      - redis_pochtman
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      DATABASE_URL: postgres://postgres:postgres@db_pochtman:5432/pochtman
      REDIS_URL: redis://redis_pochtman:6379/0

  nginx_pochtman:
    image: nginx:latest
    build:
      context: ./proxy
    restart: always
    volumes:
      - static-pochtman_data:/vol/static/
    ports:
      - "80:80"
    depends_on:
      - web_pochtman

volumes:
  db_pochtman_data:
  static-pochtman_data: