# Generated by Django 5.0 on 2024-01-15 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64, unique=True)),
                ('field_type', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('DATE', 'Date'), ('TEXT', 'Text')], default='TEXT', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fields', models.ManyToManyField(related_name='forms', to='services.field')),
            ],
        ),
    ]
