# Generated by Django 5.0 on 2024-01-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_fielddata_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddata',
            name='uid',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
    ]
