# Generated by Django 5.0 on 2024-01-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_fielddata_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('DATE', 'Date'), ('TEXT', 'Text'), ('BOOLEAN', 'Boolean')], default='TEXT', max_length=10),
        ),
    ]
