# Generated by Django 5.0 on 2024-02-07 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_fielddata_read_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddata',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='services.templateform'),
        ),
    ]
