# Generated by Django 5.0 on 2024-02-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_fielddata_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateform',
            name='tg_list',
            field=models.TextField(blank=True, max_length=164, null=True),
        ),
    ]
