# Generated by Django 5.0 on 2024-02-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_templateform_tg_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateform',
            name='tg_list',
        ),
    ]
