# Generated by Django 5.0 on 2024-02-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_remove_templateform_tg_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateform',
            name='email_author',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='templateform',
            name='telegram_author',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
