# Generated by Django 5.0 on 2024-02-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_templateform_email_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateform',
            name='email_author',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='templateform',
            name='telegram_author',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
