# Generated by Django 5.0 on 2024-05-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_templateform_email_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fielddata',
            options={'ordering': ('-time_add',)},
        ),
        migrations.AddField(
            model_name='templateform',
            name='check_ip_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templateform',
            name='ip_address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
