name: Deploy

on:
  workflow_run:
    workflows: [ Bump version, Django Testing ]
    types:
      - completed
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up SSH key
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts

        - name: Pull latest code and restart Docker
          run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_USER }}@${{ secrets.HOST_IP }} "cd pochtman/ && git pull && docker-compose up -d --build"